### ISSUE TITLE
Make error in while build the firmware and Gazebo plugins.

### ISSUE THREAD

**Issue by jaatbaba826** [gtfactslab/Llanes_ICRA2024#3]
Hey, 

I am facing the issue while running the "make all" inside the /Llanes_ICRA2024/crazyflie-firmware/sitl_make/build. I have attached a screenshot for your reference. 

![issue](https://github.com/gtfactslab/Llanes_ICRA2024/assets/52920352/391c379e-4135-4e0d-bc60-7eaf7cd14f1e)

**Comment by llanesc** [comment]
Do you have Python installed? Also try installing this:

```bash
sudo apt install python-is-python3
```

**Comment by jaatbaba826** [comment]
python3 was there. It worked after `sudo apt install python-is-python3`. Thanks.
